server:
  port: 8082

spring:
  application:
    name: planner-service
  config:
    import: 'optional:nacos:planner-service.yml'
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.171.135:3306/learning_planner?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: '123456'
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.171.135:8848
      config:
        server-addr: 192.168.171.135:8848
        file-extension: yml
  data:
    redis:
      host: 192.168.171.135
      port: 6379
      password: redis123
  rabbitmq:
    host: 192.168.171.135
    port: 5672
    username: admin
    password: admin123
    publisher-confirm-type: correlated
    publisher-returns: true

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.learningplanner.common.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto

sa-token:
  token-name: Authorization
  timeout: 2592000
  is-concurrent: true
  token-style: uuid
  jwt-secret-key: aiplanner-jwt-secret-key-2024
